// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwe351uNnZ-Y3Oy5xmcgldn52xrpJfBxE',
    appId: '1:635963078929:web:df147543d5e5855a4434b0',
    messagingSenderId: '635963078929',
    projectId: 'storeapp-65caf',
    authDomain: 'storeapp-65caf.firebaseapp.com',
    storageBucket: 'storeapp-65caf.firebasestorage.app',
    measurementId: 'G-SCEZH8NJK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf23YFxBEubiNCe_bMgFTLDGIPQzusofY',
    appId: '1:635963078929:android:f74fe6ad348348114434b0',
    messagingSenderId: '635963078929',
    projectId: 'storeapp-65caf',
    storageBucket: 'storeapp-65caf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqsZ-m1EhPjE87RlcizrIe1luRiVm7WJY',
    appId: '1:635963078929:ios:05ca566d373920604434b0',
    messagingSenderId: '635963078929',
    projectId: 'storeapp-65caf',
    storageBucket: 'storeapp-65caf.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqsZ-m1EhPjE87RlcizrIe1luRiVm7WJY',
    appId: '1:635963078929:ios:05ca566d373920604434b0',
    messagingSenderId: '635963078929',
    projectId: 'storeapp-65caf',
    storageBucket: 'storeapp-65caf.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwe351uNnZ-Y3Oy5xmcgldn52xrpJfBxE',
    appId: '1:635963078929:web:7ce24a81114433154434b0',
    messagingSenderId: '635963078929',
    projectId: 'storeapp-65caf',
    authDomain: 'storeapp-65caf.firebaseapp.com',
    storageBucket: 'storeapp-65caf.firebasestorage.app',
    measurementId: 'G-8JCST36N0X',
  );
}
